name: Build
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2
        target: esp32s3
        path: './'
    - name: Upload update binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/owl.bin
        asset_name: owl-esp32s3.bin
        tag: ${{ github.ref }}
        release_name: Release build for esp32s3
        overwrite: true
        make_latest: false
        body: ${{ github.event.pull_request.title }}
    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip
        pip install esptool
    - name: Merge binaries
      run: |
        python -m esptool --chip esp32s3 merge_bin -o combined.bin --flash_mode dio --flash_size 8MB --flash_freq 80m 0x0 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0xd000 build/ota_data_initial.bin 0x10000 build/owl.bin
    - name: Upload full binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: combined.bin
        asset_name: owl-full-esp32s3.bin
        tag: build
        release_name: Release build for esp32s3
        overwrite: true
        make_latest: false
        body: ${{ github.event.pull_request.title }}
